### ISSUE TITLE
Comparing ResNet-FC vs ResNet-CTC

### ISSUE THREAD

**Issue by alwc** [Media-Smart/vedastr#1]
Hi folks,

The code of this repo is quite clean! Good job. I'm just wondering do you have the results for ResNet-CTC? I'm curious whether it is worth spending extra time training the model with CTC (i.e. I can't figure out how to train CTC with mixed-precision). Thanks!

**Comment by ChaseMonsterAway** [comment]
@alwc Hi,
You can get the performance of ResNet-CTC in [What Is Wrong With Scene Text Recognition Model Comparisons? Dataset and Model Analysis](https://arxiv.org/abs/1904.01906).

**Comment by alwc** [comment]
@ChaseMonsterAway Am I correct to say that your ResNet-FC model is better than the ResNet-CTC model in the paper?

![image](https://user-images.githubusercontent.com/1621953/78245795-aa00cc80-751a-11ea-841f-4588fd226a0a.png)

**Comment by ChaseMonsterAway** [comment]
@alwc  We increase the channels of ResNet in ResNet-FC. So i'm not sure whether ResNet-CTC will get better performance when increase the channels of ResNet.
