### ISSUE TITLE
Models are password protected

### ISSUE THREAD

**Issue by YacobBY** [Media-Smart/vedastr#10]
Hello,
I was taking a look at the code and wanted to try your Small-Satrn model, but I cannot access it as it is password protected. Could you provide the password or remove the password protection? Thanks in advance.

**Comment by ChaseMonsterAway** [comment]
> Hello,
> I was taking a look at the code and wanted to try your Small-Satrn model, but I cannot access it as it is password protected. Could you provide the password or remove the password protection? Thanks in advance.

Hi, 
Sorry about that, i have removed the password protection.

**Comment by sasi143** [comment]
@ChaseMonsterAway It will be really helpful if you can share the link of model

**Comment by ChaseMonsterAway** [comment]
> @ChaseMonsterAway It will be really helpful if you can share the link of model

You can find the link [here](https://github.com/Media-Smart/vedastr#benchmark-and-model-zoo).
