### ISSUE TITLE
Small-SATRN infer time

### ISSUE THREAD

**Issue by whuhangzhang** [Media-Smart/vedastr#12]
When I use https://github.com/clovaai/deep-text-recognition-benchmark for the experiment, the model of the experiment is TPS-ResNet-BiLSTM-Attention, when the batch size is 1, TPS-ResNet-BiLSTM -Attention's derivation time is about 30ms, but when using the small-SATRN model, the inference time becomes 300ms. Is there any problem? Why does small-SATRN reason so long?

ref:
https://github.com/Media-Smart/vedastr/blob/93924e917bca1d5eada3bbeaf8ac7e5ba66d3de1/vedastr/runner/runner.py#L139-L154

**Comment by ChaseMonsterAway** [comment]
> When I use https://github.com/clovaai/deep-text-recognition-benchmark for the experiment, the model of the experiment is TPS-ResNet-BiLSTM-Attention, when the batch size is 1, TPS-ResNet-BiLSTM -Attention's derivation time is about 30ms, but when using the small-SATRN model, the inference time becomes 300ms. Is there any problem? Why does small-SATRN reason so long?
> 
> ref:
> https://github.com/Media-Smart/vedastr/blob/93924e917bca1d5eada3bbeaf8ac7e5ba66d3de1/vedastr/runner/runner.py#L139-L154

SATRN is bigger than TPS-ResNet-BiLSTM-Attention and thus it will spend more time.

**Comment by whuhangzhang** [comment]
@ChaseMonsterAway 
Isn't this article using the transfer module, why is the speed slower than the LSTM when calculating, I look forward to your answer，thank you~

**Comment by ChaseMonsterAway** [comment]
@whuhangzhang 
Yes, this artical use the transformer module, but his model is too big. You can write a small demo to test them.
