### ISSUE TITLE
Testing on spetial characters?

### ISSUE THREAD

**Issue by zobeirraisi** [Media-Smart/vedastr#21]
Thanks for your wonderful repo.
I tested small_SATRN on the images with special characters, but it outputs poor performance?
I changed the `test_sensitive = True` and  `test_character = ''0123456789abcdefghijklmnopq' \
            'rstuvwxyzABCDEFGHIJKLMNOPQRS' \
            'TUVWXYZ!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~''`
but I still did not get results on special characters, while this model has been trained on all characters? How we can fix it?

**Comment by ChaseMonsterAway** [comment]
Do you mean inference?

**Comment by ChaseMonsterAway** [comment]
I test the inference and it output the correct sensitive results.

**Comment by zobeirraisi** [comment]
> Do you mean inference?

yes, and I also created a model with .lmdb format that contains special characters but the model didn't recognize the special characters?

**Comment by ChaseMonsterAway** [comment]
Can you show me the result?

**Comment by ChaseMonsterAway** [comment]
> > Do you mean inference?
> 
> yes, and I also created a model with .lmdb format that contains special characters but the model didn't recognize the special characters?

which command did you used? ``python tools/inference.py configs/tps_resnet_bilstm_attn.py checkpoint_path img_path
``  or ``python tools/test.py configs/tps_resnet_bilstm_attn.py checkpoint_path``?

**Comment by zobeirraisi** [comment]
I used this command:
`python tools/inference.py configs/small_satrn.py models/Small-SATRN.pth demo_images`
and these are my configuration:
`test_sensitive = True
test_character = character`

my image labels are : 
`(A12)`, `Tiffany's`, `(1958)`, `9. -12`, 

but the results are:
2020-08-13 22:13:30,604 - INFO - Use GPU 0
2020-08-13 22:13:30,604 - INFO - Set cudnn deterministic False
2020-08-13 22:13:30,604 - INFO - Set cudnn benchmark True
2020-08-13 22:13:30,604 - INFO - Set seed 1111
2020-08-13 22:13:30,605 - INFO - Build model
2020-08-13 22:13:30,609 - INFO - GResNet init weights
2020-08-13 22:13:30,896 - INFO - TransformerEncoder init weights
2020-08-13 22:13:31,223 - INFO - TransformerDecoder init weights
2020-08-13 22:13:31,283 - INFO - TransformerHead init weights
2020-08-13 22:13:32,805 - INFO - Load checkpoint from models/Small-SATRN.pth
2020-08-13 22:13:33,273 - INFO - demo_images/word_33.png	 **['CA12Y']**
2020-08-13 22:13:33,358 - INFO - demo_images/word_955.png	 **['Tiffanyls']**
2020-08-13 22:13:33,444 - INFO - demo_images/word_999.png	 **['11958j']**
2020-08-13 22:13:33,530 - INFO - demo_images/word_1047.png	 **['9x12']**

and I also used the test command while `test_sensitive=True`  as follows and when I print the prediction all the special characters were missed.
`python tools/test.py configs/small_satrn.py models/Small-SATRN.pth
`

**Comment by ChaseMonsterAway** [comment]
> I used this command:
> `python tools/inference.py configs/small_satrn.py models/Small-SATRN.pth demo_images`
> and these are my configuration:
> `test_sensitive = True test_character = character`
> 
> my image labels are :
> `(A12)`, `Tiffany's`, `(1958)`, `9. -12`,
> 
> but the results are:
> 2020-08-13 22:13:30,604 - INFO - Use GPU 0
> 2020-08-13 22:13:30,604 - INFO - Set cudnn deterministic False
> 2020-08-13 22:13:30,604 - INFO - Set cudnn benchmark True
> 2020-08-13 22:13:30,604 - INFO - Set seed 1111
> 2020-08-13 22:13:30,605 - INFO - Build model
> 2020-08-13 22:13:30,609 - INFO - GResNet init weights
> 2020-08-13 22:13:30,896 - INFO - TransformerEncoder init weights
> 2020-08-13 22:13:31,223 - INFO - TransformerDecoder init weights
> 2020-08-13 22:13:31,283 - INFO - TransformerHead init weights
> 2020-08-13 22:13:32,805 - INFO - Load checkpoint from models/Small-SATRN.pth
> 2020-08-13 22:13:33,273 - INFO - demo_images/word_33.png **['CA12Y']**
> 2020-08-13 22:13:33,358 - INFO - demo_images/word_955.png **['Tiffanyls']**
> 2020-08-13 22:13:33,444 - INFO - demo_images/word_999.png **['11958j']**
> 2020-08-13 22:13:33,530 - INFO - demo_images/word_1047.png **['9x12']**
> 
> and I also used the test command while `test_sensitive=True` as follows and when I print the prediction all the special characters were missed.
> `python tools/test.py configs/small_satrn.py models/Small-SATRN.pth `

Firstly, the model is trained in sensitive mode. The reason why the model can't recognize the special character is: the data (download in [here](https://github.com/clovaai/deep-text-recognition-benchmark)) we used doesn't contain special characters. You can check that data by yourself. And we will re-train our model in the future.

**Comment by ChaseMonsterAway** [comment]
Also, you can use the repo to train a new model based your data.
