### ISSUE TITLE
what make model improve ?

### ISSUE THREAD

**Issue by nightfuryyy** [Media-Smart/vedastr#29]
Thank you for awesome repo.
I saw your accuracy model (tps_resnet_bilstm_attn) is 84.95. that is better than [this model](https://github.com/clovaai/deep-text-recognition-benchmark). 
What did you change ?
Thank you so much.

**Comment by ChaseMonsterAway** [comment]
Hi, @nightfuryyy 

In fact, the accuracy of tps_resnet_bilstm_attn of version 1.1.0 is 83.98 (the accuracy in is wrong ), and the model release by [deep-text-recognition-benchmark](https://github.com/clovaai/deep-text-recognition-benchmark) is 83.897.  84.95 is a mistake becasue i didn't turn off the data filter, thus the accuracy of ic15 & cute80 are wrong.

In current version (2.0.0), the better performance of tps_resnet_bilstm_attn benifit from the data. The size of ST dataset we used is larger (about 200k, total 5.7M).
