### ISSUE TITLE
Whether to try on the Chinese datasets?

### ISSUE THREAD

**Issue by whuhangzhang** [Media-Smart/vedastr#3]
Thank you for your great work. Have you ever experimented with Chinese data sets? Can you provide some other configuration, such as CRNN algorithm, etc

**Comment by ChaseMonsterAway** [comment]
@whuhangzhang , hi
We haven't experimented with chinese data sets. It's easy to implement CRNN by modifying tps-resnet-bilstm-attn configure file. We will implement other str algorithms in the future.

**Comment by whuhangzhang** [comment]
Thanks for your reply @ChaseMonsterAway . I will make some experiments on the Chinese dataset, so I hope you can give me some Suggestions. For example, whether the resnet-fc model can work for the text recognition classification of 6000+ words? Any Suggestions on preprocessing of text？thank you！

**Comment by ChaseMonsterAway** [comment]
It will take up lots of memory.
