### ISSUE TITLE
How to finetune training

### ISSUE THREAD

**Issue by Wzj02200059** [Media-Smart/vedastr#30]
Hello,
I want to know how to finetune training,
Pls tell me what should i do。。
I try to modify the config “resume=None” from None to my checkpoint file，But its not work。

**Comment by ChaseMonsterAway** [comment]
Modify as follows:
```python
resume = dict(
    checkpoint='your checkpoint file path',
    resume_optimizer=False,
    resume_lr_scheduler=False,
    resume_meta=False,
)

**Comment by Wzj02200059** [comment]
Okay~ Thank u so much ！！！

**Comment by vardhanaleti** [comment]
Hey, 
I'm new to saving models in pytorch. 
I'd like to know the file extension that is to be used. I've tried creating a .pt file, but it doesn't seem to work. 

Thank you.

**Comment by ChaseMonsterAway** [comment]
@vardhanaleti 
What do you mean 'creating a .pth file'? How do you create it?

**Comment by vardhanaleti** [comment]
I didn't understand the part where we have to specify the checkpoint file's path. 
So, I created an empty file with a .pt extension and specified this file's path in the resume dictionary. 

I don't know if I'm doing it right and I need some guidance regarding this. 
Thank you.

**Comment by ChaseMonsterAway** [comment]
@vardhanaleti 
[Here](https://github.com/Media-Smart/vedastr/blob/0fd2a0bd7819ae4daa2a161501e9f1c2ac67e96a/vedastr/runners/train_runner.py#L211) is the code part of resuming. 
To specify the checkpoint path , you can modify the config file as follows:
```
resume = dict(
    checkpoint='your checkpoint file path',
    resume_optimizer=False,
    resume_lr_scheduler=False,
    resume_meta=False,
)

**Comment by vardhanaleti** [comment]
Thank you very much

**Comment by ChaseMonsterAway** [comment]
> Thank you very much

You're welcome.
