### ISSUE TITLE
How to modify the net architecture？

### ISSUE THREAD

**Issue by Wzj02200059** [Media-Smart/vedastr#32]
Hi~ 
Thanks  for this awesome repo。
I have a question，i have noticed that the backbone network used several pooling layer，
I think its not conducive to very small size、resolution img，
so i just want to reduce the pooling layer and add dilated conv，
pls give me some advice that how to modify it。
thanks~

**Comment by ChaseMonsterAway** [comment]
Hi, could you tell me which config file you want to modify?

**Comment by Wzj02200059** [comment]
tps_resnet_bilstm_attn.py
and small_satrn.py
thx

**Comment by ChaseMonsterAway** [comment]
The params of ConvModule are [here](https://github.com/Media-Smart/vedastr/blob/261109740b31fd49a30542304176f341bcef60db/vedastr/models/utils/conv_module.py#L43). 
So, if you want to add a dilation params, you can modify a ConvModule as follows:
```python
 ('conv', dict(type='ConvModule', in_channels=1, out_channels=32, kernel_size=3,
               stride=1, padding=1, norm_cfg=norm_cfg, dilation=1))

**Comment by Wzj02200059** [comment]
OK，i got it
