### ISSUE TITLE
error after remove train_dataset_st

### ISSUE THREAD

**Issue by Wzj02200059** [Media-Smart/vedastr#34]
I delete 'train_dataset_st' in config file：
train_dataset_mj = [dict(type='FolderDataset', root='/xx/train')]
# train_dataset_st = [dict(type='FolderDataset', root='/xx/xx')]
# dict(
                    #     type='ConcatDatasets',
                    #     datasets=train_dataset_st,
                    # )
and then when i training the model， an error is ：
 File "tools/../vedastr/dataloaders/samplers/balance_sampler.py", line 75, in __iter__                                                                          indices += indices_[idx3][idx2 * size:(idx2 + 1) * size]                                                                                                 
IndexError: list index out of range

**Comment by ChaseMonsterAway** [comment]
Hi, @Wzj02200059 
First of all, if you only have one dataset, don't use balance sampler please.  Then you should change the dataset based on validation dataset which only use one dataset.

**Comment by ChaseMonsterAway** [comment]
Here is an example:
```python
    train_dataset_st = dict(type='LmdbDataset', root=train_root_st, **dataset_params)
     train=dict(
         dataloader=dict(
             type='DataLoader',
             batch_size=batch_size,
             num_workers=4,
         ),
         dataset=train_dataset_st,
         transform=train_transforms,
     )

**Comment by Wzj02200059** [comment]
ok，thx a lot
