### ISSUE TITLE
What is the mean of best_edit and edit parameters？

### ISSUE THREAD

**Issue by Wzj02200059** [Media-Smart/vedastr#38]
and what is the difference of saved models between best_acc.pth and best_norm.pth
Thx

**Comment by ChaseMonsterAway** [comment]
best_acc: The model which have the best word accuracy on validation dataset.
best_norm: The model which have the best norm edit distance on validation dataset.

**Comment by Wzj02200059** [comment]
ok，so what is the mean of edit。。。

**Comment by ChaseMonsterAway** [comment]
Normed edit distance.
