### ISSUE TITLE
How to fine tuning with different character length

### ISSUE THREAD

**Issue by chuan298** [Media-Smart/vedastr#40]
I want to fine tune training your small_satrn model with different character length. What do I ignore layers? In deep-text-recognition-benchmark, I see they ignore state Prediction. Thank you.

**Comment by ChaseMonsterAway** [comment]
Please use the sampler branch, and set the resume as follows:
```python
resume = dict(
    checkpoint='your checkpoint file path',
    resume_optimizer=False,
    resume_lr_scheduler=False,
    resume_meta=False,
    strict=False,
)

**Comment by ChaseMonsterAway** [comment]
If you have any other problems, you could reopen this issue.

**Comment by chuan298** [comment]
I did so but I get error about mismatched shape

**Comment by chuan298** [comment]
my characters are "abcdefghijklmnopqrstuvwxyz "

**Comment by ChaseMonsterAway** [comment]
It should have mismatched shape because the last several layers have different shape. But the other layers will be loaded correctly.

**Comment by ChaseMonsterAway** [comment]
What do you mean 'get error about mismatched shape'? Like this?

![image](https://user-images.githubusercontent.com/58807745/95814005-df993480-0d4b-11eb-90f5-2442ce87504f.png)

**Comment by chuan298** [comment]
> What do you mean 'get error about mismatched shape'? Like this?
> 
> ![image](https://user-images.githubusercontent.com/58807745/95814005-df993480-0d4b-11eb-90f5-2442ce87504f.png)

Yes, how can i config to ignore last serveral layers?

**Comment by chuan298** [comment]
Wait, shape of head.generator.weight, head.generator.bias, head.embedding.weight error, Have I to ignore type="TransformerHead"?

**Comment by ChaseMonsterAway** [comment]
I think it's okay. This means the model load state dict of all layers except head layer.
What do you mean ignore last several layers?

**Comment by ChaseMonsterAway** [comment]
Can you show me the content of your command?

**Comment by chuan298** [comment]
Here is my error
![image](https://user-images.githubusercontent.com/46794350/95814535-d3f63f80-0d44-11eb-8b41-4658a3134ab0.png)
I think this error is due to different character length.

**Comment by chuan298** [comment]
> Please use the sampler branch, and set the resume as follows:
> 
> ```python
> resume = dict(
>     checkpoint='your checkpoint file path',
>     resume_optimizer=False,
>     resume_lr_scheduler=False,
>     resume_meta=False,
>     strict=False,
> )
> ```

My code just change this part and character = 'abcdefghijklmnopqrstuvwxyz ', sensitive = False

**Comment by ChaseMonsterAway** [comment]
I don't have this problem after change the character to 'a~z'.
![image](https://user-images.githubusercontent.com/58807745/95814931-3273eb80-0d4e-11eb-966d-013f650ecd50.png)

Can you tell me where have you modified in config file and the environment?

**Comment by chuan298** [comment]
> I don't have this problem after change the character to 'a~z'.
> ![image](https://user-images.githubusercontent.com/58807745/95814931-3273eb80-0d4e-11eb-966d-013f650ecd50.png)
> 
> Can you tell me where have you modified in config file and the environment?

Oh sorry I forgot adding argument 'strict' but func resume in file train_runner.py have not argument 'strict'
![image](https://user-images.githubusercontent.com/46794350/95815449-e07b9780-0d46-11eb-93c4-314c99bf56cb.png)

**Comment by ChaseMonsterAway** [comment]
You should checkout the branch to sampler first.  Have a nice day!
