### ISSUE TITLE
Model performance issues

### ISSUE THREAD

**Issue by duxiangcheng** [Media-Smart/vedastr#45]
Thank you for the code. The question is the performance of the model does not look very good on the IIIT5K dataset compared to other approaches(e.g., ASTER ).  But the IIIT dataset is regular. What do you think is the problem? Looking forward to your reply.

**Comment by ChaseMonsterAway** [comment]
There're some different settings. If you want to compare the performance between them, i recommend you to do experiments using the same settings.
