### ISSUE TITLE
Question about "GResNet" and "collect"

### ISSUE THREAD

**Issue by AndiezPham** [Media-Smart/vedastr#49]
Hi, thank you for your framework!
I'm working on STR problem and I just glimpse your repo.
Could you help me answer two questions?

1. What is the meaning of "G" charater in "GResNet"? I think that the "G" is a special character. :D

2. In the config of repo, I caught the loc "collect=dict(type='CollectBlock', from_layer='c4'),". 
What is the purpose of using CollectBlock? Why don't you forward the last feature from the current block directly to the next block?

I hope you can explain it. Thank you!

**Comment by mileistone** [comment]
1. “G” for generalized.
2. This design is good for abstraction and modularity which is considered from the perspective of software engineering.

**Comment by phamvanlinh143** [comment]
I got it. Thank you!

**Comment by AndiezPham** [comment]
I got it. Thank you very much!
