### ISSUE TITLE
the saved model size

### ISSUE THREAD

**Issue by haoyuanz13** [Media-Smart/vedastr#5]
why the trained model size is 2.0G each .pth file?

**Comment by ChaseMonsterAway** [comment]
The default pth file will save model and optimizer. The size of my trained model is 500M. Maybe your model is too large.

**Comment by haoyuanz13** [comment]
hmm i just clone the code and run the demo config...

**Comment by ChaseMonsterAway** [comment]
which config you used?

**Comment by haoyuanz13** [comment]
> which config you used?

resnet_fc.py

**Comment by ChaseMonsterAway** [comment]
> > which config you used?
> 
> resnet_fc.py

The default code will save model and optimizer, the optimizer is very large. You can turn it off, then the model size will be 600M.

**Comment by haoyuanz13** [comment]
> > > which config you used?
> > 
> > 
> > resnet_fc.py
> 
> The default code will save model and optimizer, the optimizer is very large. You can turn it off, then the model size will be 600M.

alright that makes sense now, by the way, what is the usage of saving the opt params in this case?

**Comment by ChaseMonsterAway** [comment]
> > > > which config you used?
> > > 
> > > 
> > > resnet_fc.py
> > 
> > 
> > The default code will save model and optimizer, the optimizer is very large. You can turn it off, then the model size will be 600M.
> 
> alright that makes sense now, by the way, what is the usage of saving the opt params in this case?
Just for resuming.
