### ISSUE TITLE
CSTR Code

### ISSUE THREAD

**Issue by CuongNN218** [Media-Smart/vedastr#51]
Hi, thanks for your grate works.
I'm really interested in your new paper CSTR but when I clicked the link in your paper and I didn't find your code. Did you release it ?

**Comment by yinghuozijin** [comment]
Same question.Hoping the author upload the code as soon as possible.Thanks.

**Comment by ChaseMonsterAway** [comment]
We will release the code as soon as possible.

**Comment by sergiev** [comment]
@ChaseMonsterAway hello, could you please clarify on dates. I'm currently working on thesis dedicated to STR and looking forward to expand the scope with recent classification approaches. Thank you in advance.

**Comment by ChaseMonsterAway** [comment]
@sergiev 
Hello, unless something unexpected happens, the code will released in a week from now on.

**Comment by ChaseMonsterAway** [comment]
The code is released in cstr branch.
