### ISSUE TITLE
Original Paper

### ISSUE THREAD

**Issue by PrabhjotKaurGosal** [Media-Smart/vedastr#53]
Hi, 
This is not an issue but I wanted to know where I can find a link to a paper (if one exists) that is implemented in this repository. I would like to cite the work in my project. Thanks!

**Comment by ChaseMonsterAway** [comment]
@PrabhjotKaurGosal 
There's not technical report paper for vedastr. You can cite our work as follows:

```
@misc{2020vedastr,
    title  = {vedastr: A Toolbox for Scene Text Recognition},
    author = {Sun, Jun and Cai, Hongxiang and Xiong, Yichao},
    url    = {https://github.com/Media-Smart/vedastr},
    year   = {2020}
}
```
