### ISSUE TITLE
training chinese dataset

### ISSUE THREAD

**Issue by lits901** [Media-Smart/vedastr#56]
how to train chinese dataset? there should be several points need to be modified, right?

**Comment by Single430** [comment]
@ChaseMonsterAway @hxcai @mileistone   请问有交流群吗？是否可以在 好未来等中文数据集上做一些测试？非常感谢！

**Comment by ChaseMonsterAway** [comment]
> how to train chinese dataset? there should be several points need to be modified, right?

There're some researchers used vedastr do experiments on chinese dataset.
Maybe you should change the character set in config file.

**Comment by ChaseMonsterAway** [comment]
> @ChaseMonsterAway @hxcai @mileistone 请问有交流群吗？是否可以在 好未来等中文数据集上做一些测试？非常感谢！



> @ChaseMonsterAway @hxcai @mileistone 请问有交流群吗？是否可以在 好未来等中文数据集上做一些测试？非常感谢！

You can refer to #44 for communication group.
Currently, we have no plan to train a model for chinese. You can try and pull a request!
