### ISSUE TITLE
About Batch size

### ISSUE THREAD

**Issue by superPangpang** [Media-Smart/vedastr#59]
Thank you very much for your open source code of CSTR !
But when i ran the code by only 1 gpu with batchsize of 192, i found it out of cuda memory. My graphics card has 12GB memory. In the paper, The total batchsize of 10 graphics cards is 192?

**Comment by ChaseMonsterAway** [comment]
@superPangpang 
Hi, if you want to train default `cstr` you should use 4 gpu with distributed training which command is `tools/dist_train.py configs/cstr.py 4`.
