### ISSUE TITLE
CSTR inference speed

### ISSUE THREAD

**Issue by XULU42** [Media-Smart/vedastr#63]
Thanks for your contribution for a new perspective for STR.  I just wonder the inference speed of CSTR and its comparison to resnet-CTC. Is it very slow according to model size > 700Mb while resnet-ctc is about 160Mb? Looking forward to your reply, thanks.

**Comment by ChaseMonsterAway** [comment]
There're many differences between CSTR and resnet-ctc. We have show the details of CSTR in the paper.

**Comment by XULU42** [comment]
So, it's very slow?
