### ISSUE TITLE
I came across this mistake

### ISSUE THREAD

**Issue by wanglibing727** [Media-Smart/vedastr#64]
AttributeError: 'TxtDataset' object has no attribute 'transforms'

I saw it. It has this property

**Comment by ChaseMonsterAway** [comment]
Hi, 
Could you please tell me which config file you used? Have you set the transform in config file?

**Comment by wanglibing727** [comment]
@ChaseMonsterAway Thank you for your reply, I have solved this problem, and there is another question I want to ask, is this project the algorithm implementation of SATRN? Or is it the algorithm implementation of SRN? Why do I see in "https://paperswithcode.com/sota/scene-text-recognition-on-icdar2013" that these two algorithms point to this project.

**Comment by ChaseMonsterAway** [comment]
It's SATRN not SRN.

**Comment by wanglibing727** [comment]
@ChaseMonsterAway  ok, thanks

**Comment by ChaseMonsterAway** [comment]
@wanglibing727 
You're welcome.
