### ISSUE TITLE
Chinese text recognition training

### ISSUE THREAD

**Issue by whuhangzhang** [Media-Smart/vedastr#8]
I am doing the experiment of Chinese text recognition in your project. Could you please provide the log you trained for me to make some comparison?
![image](https://user-images.githubusercontent.com/53819630/84868352-22554380-b0af-11ea-934c-f9b7e1aec590.png)

**Comment by ChaseMonsterAway** [comment]
Here is the [link](https://drive.google.com/file/d/1qNGd05pWE1TGVh2e8Csa8xvyQeBShErM/view?usp=sharing) of the log.

**Comment by whuhangzhang** [comment]
thank you ~
