### ISSUE TITLE
How to identify vertical text problems ？

### ISSUE THREAD

**Issue by whuhangzhang** [Media-Smart/vedastr#9]
Can Small-SATRN process vertical text and how can the model be trained to process both vertical and horizontal text ？ What is the reference for the SRN algorithm? Thank you very much！！

**Comment by ChaseMonsterAway** [comment]
> Can Small-SATRN process vertical text and how can the model be trained to process both vertical and horizontal text ？ What is the reference for the SRN algorithm? Thank you very much！！

Hi,
- vertical text
  - You can refer to the [On Recognizing Texts of Arbitrary Shapes with 2D Self-Attention](https://arxiv.org/pdf/1910.04396.pdf). 
  -  The SATRN model is insensitive to the rotation based on the experiments in the paper.
![image](https://user-images.githubusercontent.com/58807745/86549961-a34b8080-bf73-11ea-8712-9c6875cc771a.png)

- SRN
  - I'm sorry, we haven't finished this work yet, and the reference is [Towards Accurate Scene Text Recognition with Semantic Reasoning Networks](https://arxiv.org/pdf/2003.12294.pdf).
